accounts:
  - name: owner
    balance: 10ether
  - name: user
    balance: 10ether

deployments:
  - name: level_contract
    path: "./src/ExchangeBank.sol:ExchangeBank"
    private_key: owner_private_key

exposed:
  - level_contract_address
  - user_private_key
  - user_address

verifier: "python /app/verifier.py"
flag_path: /app/flag.txt
