accounts:
  - name: owner
    balance: 100ether
  - name: user
    balance: 10ether

deployments:
  - name: level_contract
    path: "./src/SecureVault.sol:SecureVault"
    private_key: owner_private_key
    value: "50000000000000000000"

exposed:
  - level_contract_address
  - user_private_key
  - user_address

verifier: "python /app/verifier.py"
flag_path: /app/flag.txt